"""Regenerate UdCapCD icons, reference header and articulated hand models.

Each of sixteen mesh components follows a driver pose computed from the same
31-bone skeleton sent to applications. Uses only the Python standard library;
all generated files are committed, so Python is not a build dependency.
"""
import json
import math
from pathlib import Path
import struct
import zlib

ROOT = Path(__file__).resolve().parent / "udcap/resources"
OUTLINE = [(8, 29), (8, 23), (4, 17), (2, 13), (3, 11), (5, 11),
           (9, 16), (9, 7), (10, 5), (12, 5), (13, 7), (13, 16),
           (14, 16), (14, 3), (15, 1), (17, 1), (18, 3), (18, 16),
           (19, 16), (19, 5), (20, 3), (22, 3), (23, 5), (23, 17),
           (24, 17), (24, 10), (25, 8), (27, 8), (28, 10), (28, 23),
           (25, 29)]
COLORS = {"off": (113, 123, 136), "searching": (61, 148, 223),
          "ready": (79, 199, 116), "alert": (237, 171, 65), "error": (225, 84, 78)}


def png(path, width, height, pixels):
    def chunk(kind, data):
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))
    rows = b"".join(b"\0" + bytes(pixels[y * width * 4:(y + 1) * width * 4]) for y in range(height))
    path.write_bytes(b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
                     + chunk(b"IDAT", zlib.compress(rows)) + chunk(b"IEND", b""))


def inside(x, y, poly):
    result = False
    for a, b in zip(poly, poly[1:] + poly[:1]):
        if (a[1] > y) != (b[1] > y) and x < (b[0] - a[0]) * (y - a[1]) / (b[1] - a[1]) + a[0]:
            result = not result
    return result


def icons():
    folder = ROOT / "icons"
    folder.mkdir(parents=True, exist_ok=True)
    for side in ("left", "right"):
        # Thumb points inward in the pair when viewed from the back of the hands.
        poly = [(32 - x if side == "left" else x, y) for x, y in OUTLINE]
        points = " ".join(f"{x},{y}" for x, y in poly)
        (folder / f"{side}.svg").write_text(
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">'
            f'<polygon points="{points}" fill="#8fa6bb"/></svg>\n', encoding="utf-8")
        for state, color in COLORS.items():
            for size, suffix in ((32, ""), (64, "_2x")):
                pixels = []
                for y in range(size):
                    for x in range(size):
                        coverage = sum(inside((x + (sx + .5) / 4) * 32 / size,
                                              (y + (sy + .5) / 4) * 32 / size, poly)
                                       for sx in range(4) for sy in range(4))
                        pixels.extend((*color, round(255 * coverage / 16)))
                png(folder / f"{side}_{state}{suffix}.png", size, size, pixels)


REFERENCE = json.loads(Path(__file__).with_name("hand_reference.json").read_text())["right"]
RENDER_BONES = [1, 2, 3, 4, 7, 8, 9, 12, 13, 14, 17, 18, 19, 22, 23, 24]


def reference_header():
    lines = ["// Generated by generate_hand_resources.py; edit hand_reference.json.",
             "// Valve OpenHand local joint frames (meters, wxyz), with UdCapCD wrist origin.",
             "#pragma once", "#include <openvr_driver.h>", "#include <array>",
             "inline constexpr std::array<vr::VRBoneTransform_t,26> handReferenceRight{{"]
    for bone in REFERENCE:
        p = ",".join(f"{v:.9f}f" for v in bone["position"])
        q = ",".join(f"{v:.9f}f" for v in bone["orientation"])
        lines.append("    {{{"+p+",1.0f}}, {"+q+"}},")
    lines.append("}};")
    Path(__file__).with_name("HandReferencePose.h").write_text("\n".join(lines)+"\n", encoding="utf-8")


def model(side):
    name = f"udcapc_hand_{side}"
    folder = ROOT / "rendermodels" / name
    folder.mkdir(parents=True, exist_ok=True)
    # The right skeleton's local segments extend towards -X; left is inverted.
    sign = -1 if side == "left" else 1

    def segment(a, b, radius_a, radius_b, depth=1):
        vertices, faces = [], []
        # Elliptical capped segments, with normals emitted per triangle below.
        direction = [b[i]-a[i] for i in range(3)]
        length = math.sqrt(sum(v*v for v in direction))
        tangent = [v/length for v in direction]
        other = (0, 0, 1) if abs(tangent[2]) < .9 else (1, 0, 0)
        def cross(u, v):
            return [u[1]*v[2]-u[2]*v[1], u[2]*v[0]-u[0]*v[2], u[0]*v[1]-u[1]*v[0]]
        u = cross(other, tangent)
        scale = math.sqrt(sum(v*v for v in u))
        u = [v/scale for v in u]
        v = cross(tangent, u)
        for center, radius in ((a, radius_a), (b, radius_b)):
            for j in range(12):
                angle = 2 * math.pi * j / 12
                vertices.append(tuple(center[i]+radius*(u[i]*math.cos(angle)+depth*v[i]*math.sin(angle)) for i in range(3)))
        local = []
        for j in range(12):
            k = (j + 1) % 12
            local.extend(((j, k, j + 12), (k, k + 12, j + 12)))
        for j in range(1, 11):
            local.extend(((0, j + 1, j), (12, j + 12, j + 13)))
        for face in local:
            faces.append(tuple(face))
        return vertices, faces

    components = {}
    for bone in RENDER_BONES:
        if bone == 1:
            vertices, faces = segment((0,0,.005),(0,0,.078),.025,.038,.3)
        else:
            end = tuple(sign*v for v in REFERENCE[bone+1]["position"])
            radius = .009 if bone < 5 else .008 if bone < 22 else .007
            vertices, faces = segment((0,0,0),end,radius,radius*.85)
        lines = [f"mtllib {name}.mtl", f"o bone_{bone}", "usemtl glove", "vt 0.5 0.5"]
        lines.extend("v %.7f %.7f %.7f" % v for v in vertices)
        for index, face in enumerate(faces):
            a, b, c = [vertices[i] for i in face]
            u, v = [b[i]-a[i] for i in range(3)], [c[i]-a[i] for i in range(3)]
            n = [u[1]*v[2]-u[2]*v[1], u[2]*v[0]-u[0]*v[2], u[0]*v[1]-u[1]*v[0]]
            norm = math.sqrt(sum(t*t for t in n))
            lines.append("vn %.7f %.7f %.7f" % tuple(t/norm for t in n))
            lines.append("f "+" ".join(f"{i+1}/1/{index+1}" for i in face))
        filename = f"bone_{bone}.obj"
        (folder/filename).write_text("\n".join(lines)+"\n",encoding="utf-8")
        components[f"bone_{bone}"] = {"filename":filename, "motion":{
            "type":"pose_component", "pose_path":f"/pose/udcapc_bone_{bone}"}}
    (folder / f"{name}.mtl").write_text("newmtl glove\nKa 0.2 0.2 0.2\nKd 1 1 1\nKs 0.1 0.1 0.1\nNs 12\nmap_Kd glove.png\n", encoding="utf-8")
    png(folder / "glove.png", 1, 1, [142, 166, 189, 255])
    (folder / f"{name}.json").write_text(json.dumps({"components":components}, indent=2)+"\n", encoding="utf-8")


if __name__ == "__main__":
    reference_header()
    icons()
    model("left")
    model("right")
