//
// Created by max_3 on 2025/6/6.
//

#ifndef UDCAPCOMMUNITYDRIVERUI_CONFIG_H
#define UDCAPCOMMUNITYDRIVERUI_CONFIG_H

enum UdCapDriverType {
    UD_CAP_DRIVER_TYPE_CONSUMER = 0,
    UD_CAP_DRIVER_TYPE_ENTERPRISE = 1
};

#endif //UDCAPCOMMUNITYDRIVERUI_CONFIG_H
